### ISSUE TITLE
feature: add dockerfile to project

### ISSUE THREAD

**Issue by LeonardoSantosBR** [plotwist-app/plotwist#184]

**Comment by eulixir** [comment]
Hi @LeonardoSantosBR, how are you?

When we talk about open source projects. Some gentlemen's agreements are necessary to organise what goes in and out of the project, and for the maintainers to have some control over these changes.

It's very important to tell us what the issue is, what you're trying to solve with it, what you miss about the project? It's interesting to use the description part of the issue and provide this information (I'll create a file to make it easier to fill in).
 
 



Translated with www.DeepL.com/Translator (free version)
