### ISSUE TITLE
Bug: The username is not unique (capitalization)

### ISSUE THREAD

**Issue by Suburbanno** [plotwist-app/plotwist#337]
The username must be unique regardless of capitalization. If you have a user registered as "TheName", it is no longer possible to register that user using capitalization, such as "theName", "Thename" or "thename".

Example of what is currently possible

https://plotwist.app/en-US/vinicius
https://plotwist.app/en-US/Vinicius

**Comment by lui7henrique** [comment]
Fixed! @Suburbanno

**Comment by Vicentesan** [comment]
This issue is not fixed, and the problem can be fixed in two ways:

1. forcing the username to be lowercased here
![image](https://github.com/user-attachments/assets/3b326f4d-8ddb-44c8-8eef-0b0b81321cf9)

2. forcing the username to be lowercased here
![image](https://github.com/user-attachments/assets/008e419d-0c50-4a18-a8e6-6fe83cdcdb3b)


or we could do it in both sides to ensure safety hahaha, what do u guys think about?

**Comment by lui7henrique** [comment]
@Vicentesan 

This was adjusted by the database schema

![image](https://github.com/user-attachments/assets/7f120fd5-0339-4f4d-84c1-2aa1fc523440)
